import { solvePart1, solvePart2 } from "../../src/2024/day8";

describe("Day 5 solution", () => {
  const exampleInput = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;
  describe("Part 1", () => {
    it("can solve example input", () => {
      const result = solvePart1(exampleInput);
      expect(result).toBe(14);
    });
  });
  describe("Part 2", () => {
    it("can solve example input", () => {
      const result = solvePart2(exampleInput);
      expect(result).toBe(34);
    });
  });
});
